server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: PRODUCTS-SERVER
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

mybatis:
  type-aliases-package: com.lsk.products.domain

  mapper-locations: classpath:/productsDao/*.xml
